# Site Settings
lang: en
title: IPM-OAM
tagline: IPM-OAM
email: your-email@domain.com
description: >
  IPM Observational Astronomy Meetings (OAM) are the informal seminars of the Observational Astronomy Group at the School of Astronomy (SoA) in the Institute of Research in Fundamental Sciences (IPM).
#baseurl: "/bulma-clean-theme"
#url: "https://www.csrhymes.com"
permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
#disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
#  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

#defaults:
#  -
#    scope:
#      path: ""
#      type: "pages"
#    values:
#      show_sidebar: true
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      author: "C.S. Rhymes"
#      layout: post
#      image: https://via.placeholder.com/1200x800
#      show_sidebar: true

markdown: kramdown
highlighter: rouge

#footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
